version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest #php7.3-fpm-alpine
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:${MYSQL_TCP_PORT}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:4.8
     depends_on:
       - db
     restart: always
     ports:
       - "10005:80"
     environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=db
       - PMA_PORT=${MYSQL_TCP_PORT}
volumes:
    db_data: {}

