FROM jenkins/jenkins:lts

USER  root

RUN apt update && apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
         apt-key fingerprint 0EBFCD88 && \
         add-apt-repository \
         "deb [arch=amd64] https://download.docker.com/linux/debian \
         $(lsb_release -cs) stable"

RUN apt update && apt install -y docker docker-ce docker-ce-cli containerd.io  && \
         apt-get clean && \
         rm -rf /var/lib/apt/lists/*
         
RUN systemctl enable docker && service docker start

RUN curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
